references = {
    "Beck2017WordSized": {
        "abstract": "Generating visualizations at the size of a word creates dense information representations often called sparklines. The integration of word-sized graphics into text could avoid additional cognitive load caused by splitting the readers\u2019 attention between figures and text. In scientific publications, these graphics make statements easier to understand and verify because additional quantitative information is available where needed. In this work, we perform a literature review to find out how researchers have already applied such word-sized representations. Illustrating the versatility of the approach, we leverage these representations for reporting empirical and bibliographic data in three application examples. For interactive Web-based publications, we explore levels of interactivity and discuss interaction patterns to link visualization and text. We finally call the visualization community to be a pioneer in exploring new visualization-enriched and interactive publication formats.",
        "author": "Beck, Fabian and Weiskopf, Daniel",
        "doi": "10.1109/TVCG.2017.2674958",
        "journal": "IEEE Transactions on Visualization and Computer Graphics",
        "keywords": "domain:infovis, domain:publishing, type:survey, type:theory, augmented_text, sparklines, interaction, bibliometrics, eye-tracking_visualization",
        "number": "6",
        "pages": "1576--1587",
        "publisher": "IEEE",
        "series": "TVCG",
        "title": "Word-Sized Graphics for Scientific Texts",
        "type": "article",
        "volume": "23",
        "year": "2017"
    },
    "Brandes2011Asymmetric": {
        "abstract": "In modeling and analysis of longitudinal social networks, visual exploration is used in particular to complement and inform other methods. The most common graphical representations for this purpose appear to be animations and small multiples of intermediate states, depending on the type of media available. We present an alternative approach based on matrix representation of gestaltlines (a combination of Tufte's sparklines with glyphs based on gestalt theory). As a result, we obtain static, compact, yet data-rich diagrams that support specifically the exploration of evolving dyadic relations and persistent group structure, although at the expense of cross-sectional network views and indirect linkages.",
        "author": "Brandes, Ulrik and Nick, Bobo",
        "citeulike-article-id": "9861061",
        "doi": "10.1109/TVCG.2011.169",
        "journal": "IEEE Transactions on Visualization and Computer Graphics",
        "keywords": "domain:social_network, domain:infovis, augmented_text, dynamic_graph, gestalt_theory, graph_vis, matrix, sparklines",
        "number": "12",
        "pages": "2283--2290",
        "title": "Asymmetric Relations in Longitudinal Social Networks",
        "type": "article",
        "volume": "17",
        "year": "2011"
    },
    "Goffin2014Exploring": {
        "abstract": "We present an exploration and a design space that characterize the usage and placement of word-scale visualizations within text documents. Word-scale visualizations are a more general version of sparklines-small, word-sized data graphics that allow meta-information to be visually presented in-line with document text. In accordance with Edward Tufte's definition, sparklines are traditionally placed directly before or after words in the text. We describe alternative placements that permit a wider range of word-scale graphics and more flexible integration with text layouts. These alternative placements include positioning visualizations between lines, within additional vertical and horizontal space in the document, and as interactive overlays on top of the text. Each strategy changes the dimensions of the space available to display the visualizations, as well as the degree to which the text must be adjusted or reflowed to accommodate them. We provide an illustrated design space of placement options for word-scale visualizations and identify six important variables that control the placement of the graphics and the level of disruption of the source text. We also contribute a quantitative analysis that highlights the effect of different placements on readability and text disruption. Finally, we use this analysis to propose guidelines to support the design and placement of word-scale visualizations.",
        "author": "Goffin, Pascal and Willett, Wesley and Fekete, Jean-Daniel and Isenberg, Petra",
        "doi": "10.1109/TVCG.2014.2346435",
        "journal": "IEEE Transactions on Visualization and Computer Graphics",
        "keywords": "augmented_text, sparklines, domain:infovis",
        "number": "12",
        "pages": "2291--2300",
        "publisher": "IEEE",
        "series": "TVCG",
        "title": "Exploring the placement and design of word-scale visualizations",
        "type": "article",
        "volume": "20",
        "year": "2014"
    },
    "Goffin2015Exploring": {
        "abstract": "We studied how the integration of small visualizations (word-scale visualizations) into a sentence affects reading speed and memorization during a brief reading task. In particular, we were interested in how different placement types with their inherent text appearance and layout changes affect readers. We designed a quantitative study in which we gave sentences with or without visualizations for participants to read. Then, we invited them to answer questions on the sentences. We found that the information encoded in the visualizations is more prominent and easily remembered than information in the written text, but that different placement options had little to no effect on reading performance, even if participants had different preferences.",
        "author": "Goffin, Pascal and Willett, Wesley and Bezerianos, Anastasia and Isenberg, Petra",
        "booktitle": "Proceedings of the 33rd Annual ACM Conference Extended Abstracts on Human Factors in Computing Systems",
        "doi": "10.1145/2702613.2732778",
        "keywords": "sparklines, reading, augmented_text, domain:infovis",
        "pages": "1827--1832",
        "publisher": "ACM",
        "series": "CHI EA",
        "title": "Exploring the Effect of Word-Scale Visualizations on Reading Behavior",
        "type": "inproceedings",
        "year": "2015"
    },
    "Goffin2017Exploratory": {
        "abstract": "We contribute an investigation of the design and function of word-scale graphics and visualizations embedded in text documents. Word-scale graphics include both data-driven representations such as word-scale visualizations and sparklines, and non-data-driven visual marks. Their design, function, and use has so far received little research attention. We present the results of an open ended exploratory study with 9 graphic designers. The study resulted in a rich collection of different types of graphics, data provenance, and relationships between text, graphics, and data. Based on this corpus, we present a systematic overview of word-scale graphic designs, and examine how designers used them. We also discuss the designers\u2019 goals in creating their graphics, and characterize how they used word-scale graphics to visualize data, add emphasis, and create alternative narratives. Building on these examples, we discuss implications for the design of authoring tools for word-scale graphics and visualizations, and explore how new authoring environments could make it easier for designers to integrate them into documents.",
        "author": "Goffin, Pascal and Boy, Jeremy and Willett, Wesley and Isenberg, Petra",
        "doi": "10.1109/TVCG.2016.2618797",
        "journal": "IEEE Transactions on Visualization and Computer Graphics",
        "keywords": "domain:infovis, evaluation:user_study, type:evaluation, sparklines, augmented_text",
        "number": "10",
        "pages": "2275--2287",
        "series": "TVCG",
        "title": "An Exploratory Study of Word-Scale Graphics in Data-Rich Text Documents",
        "type": "article",
        "volume": "23",
        "year": "2017"
    },
    "Latif2019VIS": {
        "abstract": "Publication records and collaboration networks are important for assessing the expertise and experience of researchers. Existing digital libraries show the raw publication lists in author profiles, whereas visualization techniques focus on specific subproblems. Instead, we look at publication records from various perspectives mixing low-level publication data with high-level abstractions and background information. This work presents VIS Author Profiles, a novel approach to generate integrated textual and visual descriptions to highlight patterns in publication records. We leverage template-based natural language generation to summarize notable publication statistics, evolution of research topics, and collaboration relationships. Seamlessly integrated visualizations augment the textual description and are interactively connected with each other and the text. The underlying publication data and detailed explanations of the analysis are available on demand. We compare our approach to existing systems by taking into account information needs of users and demonstrate its usefulness in two realistic application examples.",
        "author": "Latif, Shahid and Beck, Fabian",
        "doi": "10.1109/TVCG.2018.2865022",
        "journal": "IEEE Transactions on Visualization and Computer Graphics",
        "keywords": "nlg, bibliometrics, domain:infovis, interactive_documents, domain:nlg, sparklines, augmented_text",
        "number": "1",
        "pages": "152--161",
        "publisher": "IEEE",
        "title": "{VIS Author Profiles}: Interactive Descriptions of Publication Records Combining Text and Visualization",
        "type": "article",
        "volume": "25",
        "year": "2019"
    },
    "Tufte2006Beautiful": {
        "abstract": "Science and art have in common intense seeing, the wide-eyed observing that generates empirical information. Beautiful Evidence is about how seeing turns into showing, how empirical observations turn into explanations and evidence presentations. The book identifies excellent and effective methods for presenting information, suggests new designs, and provides tools for assessing the credibility of evidence presentations.Here we will see many close readings of serious evidence presentations-ranging through evolutionary trees and rocket science to economics, art history, and sculpture. Insistent application of the principles of analytical thinking helps both insiders and outsiders assess the credibility of evidence.",
        "author": "Tufte, Edward R.",
        "edition": "1st",
        "howpublished": "Hardcover",
        "isbn": "0961392177",
        "keywords": "type:textbook, infographics, sparklines, domain:infovis",
        "publisher": "Graphics Press",
        "title": "Beautiful Evidence",
        "type": "book",
        "year": "2006"
    },
};